=== boqnd/uni/FifthSemester/xml/1st_homework_xml/Schema.dtd
<?xml version="1.0" encoding="UTF-8"?>

 <!ELEMENT game_library (game*)>
 <!ELEMENT game (id, game_header, game_details)>
 <!ELEMENT id (#PCDATA)>
 <!ATTLIST id code ID #REQUIRED>

 <!--GAME HEADER -->
 <!ELEMENT game_header (game_name, price, manufacturer)>
 <!ELEMENT game_name (#PCDATA)>
 <!ELEMENT price (#PCDATA)>
 <!ELEMENT manufacturer (name,location, salary)>
 <!ELEMENT name (#PCDATA)>
 <!ELEMENT location (#PCDATA)>
 <!ELEMENT salary (#PCDATA)>

 <!--GAME DETAILS -->
 <!ELEMENT game_details (summary, publish_date?,age_restriction, operational_system , rating?, 
genres, language, publisher, authors)>
 <!ELEMENT summary (#PCDATA)>
 <!ELEMENT publish_date (date)>
 <!ELEMENT age_restriction (#PCDATA)>
 <!ELEMENT operational_system EMPTY>
 <!ATTLIST operational_system type (Windows | Mac | Linux) #REQUIRED>
 <!ELEMENT rating (#PCDATA)>
 <!ELEMENT genres (genre+)>
 <!ELEMENT genre EMPTY>
 <!ATTLIST genre name 
(Action | Adventure | Action-adventure | Role-playing | Strategy | Simulation | Puzzle | Sport | Racing | Idle) #REQUIRED>
 <!ELEMENT language EMPTY>
 <!ATTLIST language name (Bulgarian | English | Spanish | Russian | German | Greek | Turkish | Chineese | Japanese |
  French | Portugese | Polish) #REQUIRED>
 <!ELEMENT publisher (#PCDATA)>
 
 <!--AUTHORS INFO -->
 <!ELEMENT authors (author*)>
 <!ELEMENT author (author_name, biography?, published_games?, nationality?, 
birth_day?, death_day?)>
 <!ELEMENT author_name (#PCDATA)>
 <!ELEMENT biography (#PCDATA)>
 <!ELEMENT published_games (#PCDATA)>
 <!ELEMENT nationality (#PCDATA)>
 <!ELEMENT birth_day (date)>
 <!ELEMENT death_day (date)>
 <!ELEMENT date EMPTY>
 <!ATTLIST date day CDATA #IMPLIED>
 <!ATTLIST date month CDATA #IMPLIED>
 <!ATTLIST date year CDATA #IMPLIED>

=== boqnd/uni/FifthSemester/xml/hw_2_xml 2/game1.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE game_library SYSTEM "./Xml_scheme/Schema.dtd">
<game_library>
    <game>
        <id code ='G1'> </id>
        
        <game_header>
            <game_name> League of Legends </game_name>
            <price>0.00</price>
                <manufacturer>
                    <name>Riot games</name>
                <location> USA </location>
                <salary> 1000000.00</salary>
                </manufacturer>
        </game_header>

        <game_details> 
            <summary> Moba game </summary>
            <publish_date>
               <date year="2009"/>
            </publish_date>
            <age_restriction>
                13+
            </age_restriction>
            <operational_system type="Windows"/>
            <rating>
                8.0
            </rating>
            <genres>
                <genre name="Action"/>
            </genres>
            <language name="English"/>
        
            <publisher> Riot Games </publisher>
            <authors>
                <author>
                    <author_name> Tom Cadwell </author_name>
                    <biography> none </biography>
                    <published_games> League of Legends </published_games>
                    <nationality>American</nationality>
                    <birth_day>
                        <date day="3" month="7" year="1981"/>
                    </birth_day>
                    <death_day>
                        <date day="0" month="0" year="0"/>
                    </death_day>
                </author>
            </authors>
        </game_details>       
    </game>    
</game_library>

=== boqnd/uni/FifthSemester/xml/hw_2_xml 2/game2.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE game_library SYSTEM "./Xml_scheme/Schema.dtd">
<game_library>
    <game>
        <id code ='G2'> </id>
        
        <game_header>
            <game_name>Hearthstone</game_name>
            <price>0.00</price>
                <manufacturer>
                    <name> Blizzard entertainment</name>
                <location> USA </location>
                <salary> 400000.00</salary>
                </manufacturer>
        </game_header>

        <game_details> 
            <summary>Card game </summary>
            <publish_date>
               <date year="2014"/>
            </publish_date>
            <age_restriction>
                7+
            </age_restriction>
            <operational_system type="Windows"/>
            <rating>
                5.5
            </rating>
            <genres>
                <genre name="Strategy"/>
            </genres>
            <language name="English"/>
        
            <publisher> Blizzard Entertainment </publisher>
            <authors>
                <author>
                    <author_name> Dean Ayala </author_name>
                    <biography> none </biography>
                    <published_games> Hearthstone, StarCraft || , Diablo ||| </published_games>
                    <nationality>American</nationality>
                    <birth_day>
                        <date day="15" month="10" year="1980"/>
                    </birth_day>
                    <death_day>
                        <date day="0" month="0" year="0"/>
                    </death_day>
                </author>
            </authors>
        </game_details>       
    </game>    
</game_library>

=== boqnd/uni/FifthSemester/xml/hw_2_xml 2/game5.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE game_library SYSTEM "./Xml_scheme/Schema.dtd">
<game_library>
    <game>
        <id code ='G5'> </id>
        
        <game_header>
            <game_name> God of War Ragnarök </game_name>
            <price>79.99€</price>
                <manufacturer>
                    <name>Santa Monica Studio</name>
                <location>Los Angeles, USA </location>
                <salary> 5000000.00</salary>
                </manufacturer>
        </game_header>

        <game_details> 
            <summary> Action-adventure </summary>
            <publish_date>
               <date year="2022"/>
            </publish_date>
            <age_restriction>
                18+
            </age_restriction>
            <operational_system type="Linux"/>
            <rating>
                9.9
            </rating>
            <genres>
                <genre name="Action-adventure"/>
            </genres>
            <language name="English"/>
        
            <publisher>Sony Interactive Entertainment</publisher>
            <authors>
                <author>
                    <author_name>  Cory Barlog</author_name>
                    <biography> yes </biography>
                    <published_games> Requiem: Avenging Angel, God Of War, God Of War || , God of War Ragnarök </published_games>
                    <nationality>American</nationality>
                    <birth_day>
                        <date day="2" month="9" year="1975"/>
                    </birth_day>
                    <death_day>
                        <date day="0" month="0" year="0"/>
                    </death_day>
                </author>
            </authors>
        </game_details>       
    </game>    
</game_library>

=== boqnd/uni/FifthSemester/xml/hw_2_xml/game3.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE game_library SYSTEM "./Xml_scheme/Schema.dtd">
<game_library>
    <game>
        <id code ='G3'> </id>
        
        <game_header>
            <game_name> Monster Hunter: World </game_name>
            <price>69.99â‚¬</price>
                <manufacturer>
                    <name>Capcom</name>
                <location>Osaka, Japan </location>
                <salary> 10000000.00</salary>
                </manufacturer>
        </game_header>

        <game_details> 
            <summary> Action </summary>
            <publish_date>
               <date year="2018"/>
            </publish_date>
            <age_restriction>
                12+
            </age_restriction>
            <operational_system type="Mac"/>
            <rating>
                9.5
            </rating>
            <genres>
                <genre name="Action"/>
            </genres>
            <language name="Japanese"/>
        
            <publisher>Capcom</publisher>
            <authors>
                <author>
                    <author_name> Yuya Tokuda </author_name>
                    <biography> none </biography>
                    <published_games> Monster Hunter: World, Monster Hunter 4, Monster Hunter World: Iceborne </published_games>
                    <nationality>Japanese</nationality>
                    <birth_day>
                        <date day="25" month="7" year="1975"/>
                    </birth_day>
                    <death_day>
                        <date day="0" month="0" year="0"/>
                    </death_day>
                </author>
            </authors>
        </game_details>       
    </game>    
</game_library>

=== boqnd/uni/FifthSemester/xml/hw_2_xml/game4.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE game_library SYSTEM "./Xml_scheme/Schema.dtd">
<game_library>
    <game>
        <id code ='G4'> </id>
        
        <game_header>
            <game_name> F1 22 </game_name>
            <price>59.99â‚¬</price>
                <manufacturer>
                    <name>Codemasters</name>
                <location>Southam, England </location>
                <salary> 2000000.00</salary>
                </manufacturer>
        </game_header>

        <game_details> 
            <summary> Sport </summary>
            <publish_date>
               <date year="2022"/>
            </publish_date>
            <age_restriction>
                3+
            </age_restriction>
            <operational_system type="Windows"/>
            <rating>
                7.7
            </rating>
            <genres>
                <genre name="Racing"/>
            </genres>
            <language name="German"/>
        
            <publisher>EA Sports</publisher>
            <authors>
                <author>
                    <author_name> Ian Livingstone </author_name>
                    <biography> none </biography>
                    <published_games> F1 22 </published_games>
                    <nationality>English</nationality>
                    <birth_day>
                        <date day="15" month="4" year="1989"/>
                    </birth_day>
                    <death_day>
                        <date day="0" month="0" year="0"/>
                    </death_day>
                </author>
            </authors>
        </game_details>       
    </game>    
</game_library>
