=== boqnd/uni/FifthSemester/xml/hw3_72029(old)/VeterinaryClinic.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT vet_clinic (clinic*, client*, animal*, examination*)>
  <!ELEMENT client (full_name, address, phone)>
    <!ELEMENT full_name (#PCDATA)>
    <!ELEMENT address (#PCDATA)>
    <!ELEMENT phone (#PCDATA)>
  <!ELEMENT animal (name, type, breed, age)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT type (#PCDATA)>
    <!ELEMENT breed (#PCDATA)>
    <!ELEMENT age (#PCDATA)>
  <!ELEMENT examination (description, price)>
    <!ELEMENT description (#PCDATA)>
    <!ELEMENT price (#PCDATA)>
  <!ELEMENT clinic (clinic_name, clinic_location)>
    <!ELEMENT clinic_name (#PCDATA)>
    <!ELEMENT clinic_location (#PCDATA)>

<!ATTLIST client id ID #REQUIRED>
<!ATTLIST animal id ID #REQUIRED>
<!ATTLIST animal client_id IDREF #REQUIRED>
<!ATTLIST examination id ID #REQUIRED>
<!ATTLIST examination animal_id IDREF #REQUIRED>

=== boqnd/uni/FifthSemester/xml/hw2/vet1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vet_clinic SYSTEM "VeterinaryClinic.dtd">

<vet_clinic>
  <client id="c1">
    <full_name>Boyan</full_name>
    <address>Sofia</address>
    <phone>0881234567</phone>
  </client>
  <animal id="a1" client_id="c1">
    <name>Bau</name>
    <type>Dog</type>
    <breed>Street</breed>
    <age>2</age>
  </animal>
  <examination id="e2" animal_id="a1">
    <description>Grooming</description>
    <price>60</price>
  </examination>
</vet_clinic>

=== boqnd/uni/FifthSemester/xml/hw3_72029(old)/vet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vet_clinic SYSTEM "VeterinaryClinic.dtd">

<vet_clinic>
  <clinic>
    <clinic_name>FMI_CLINIC</clinic_name>
    <clinic_location>JAMES BAUCHER</clinic_location>
  </clinic>
  <client id="c1">
    <full_name>Boyan</full_name>
    <address>Sofia</address>
    <phone>0881234567</phone>
  </client>
  <client id="c2">
    <full_name>Nasko</full_name>
    <address>Haskovo</address>
    <phone>0888123456</phone>
  </client>
  <animal id="a1" client_id="c1">
    <name>Bau</name>
    <type>Dog</type>
    <breed>Street</breed>
    <age>2</age>
  </animal>
  <animal id="a2" client_id="c2">
    <name>BauBau</name>
    <type>Dog</type>
    <breed>Husky</breed>
    <age>10</age>
  </animal>
  <examination id="e1" animal_id="a2">
    <description>Grooming</description>
    <price>90</price>
  </examination>
  <examination id="e2" animal_id="a1">
    <description>Grooming</description>
    <price>60</price>
  </examination>
</vet_clinic>

=== boqnd/uni/FifthSemester/xml/hw2/vet4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vet_clinic SYSTEM "VeterinaryClinic.dtd">

<vet_clinic>
  <client id="c4">
    <full_name>Valeri</full_name>
    <address>Sofia</address>
    <phone>0881234888</phone>
  </client>
  <animal id="a4" client_id="c4">
    <name>Bari</name>
    <type>Dog</type>
    <breed>Street</breed>
    <age>2</age>
  </animal>
  <examination id="e4" animal_id="a4">
    <description>Grooming</description>
    <price>60</price>
  </examination>
</vet_clinic>

=== boqnd/uni/FifthSemester/xml/hw2/vet3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vet_clinic SYSTEM "VeterinaryClinic.dtd">

<vet_clinic>
  <client id="c3">
    <full_name>Kaloyan</full_name>
    <address>Pernik</address>
    <phone>0888834567</phone>
  </client>
  <animal id="a3" client_id="c3">
    <name>Sharo</name>
    <type>Dog</type>
    <breed>Street</breed>
    <age>5</age>
  </animal>
  <examination id="e3" animal_id="a3">
    <description>Grooming</description>
    <price>60</price>
  </examination>
</vet_clinic>

=== boqnd/uni/FifthSemester/xml/hw2/vet2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vet_clinic SYSTEM "VeterinaryClinic.dtd">

<vet_clinic>
  <client id="c2">
    <full_name>Nasko</full_name>
    <address>Haskovo</address>
    <phone>0888123456</phone>
  </client>
  <animal id="a2" client_id="c2">
    <name>BauBau</name>
    <type>Dog</type>
    <breed>Husky</breed>
    <age>10</age>
  </animal>
  <examination id="e1" animal_id="a2">
    <description>Grooming</description>
    <price>90</price>
  </examination>
</vet_clinic>

=== boqnd/uni/FifthSemester/xml/hw2/vet5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vet_clinic SYSTEM "VeterinaryClinic.dtd">

<vet_clinic>
  <client id="c5">
    <full_name>Yoan</full_name>
    <address>Sofia</address>
    <phone>0887774567</phone>
  </client>
  <animal id="a5" client_id="c5">
    <name>Kotka</name>
    <type>Cat</type>
    <breed>Street</breed>
    <age>1</age>
  </animal>
  <examination id="e5" animal_id="a5">
    <description>Grooming</description>
    <price>60</price>
  </examination>
</vet_clinic>
